# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - expensessvc

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run:  dotnet publish -c Release -o C:\Users\runneradmin\AppData\Local\Microsoft\dotnet/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet/myapp

      - name: Install EntityFrameworkCore Tools
        run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef
            
      - name: Generate EF Core Migration Script
        run: dotnet ef migrations script --idempotent --no-build --configuration Release --output C:\Users\runneradmin\AppData\Local\Microsoft\dotnet/sql/sql-script.sql --context ExpensesService.Data.ProjectContext --project ${{ github.workspace }}/ExpensesService/ExpensesService.csproj
      
      - uses: actions/upload-artifact@v3
        with:
          name: ddl-updates
          path: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet/sql\sql-script.sql

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_62754FDDC75142E9A8F4A3ECCB95BD85 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A7868ACDA38B4950B57F99835A48B0F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BB486BF555A64AB5B4AA233AC6BF3936 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'expensessvc'
          slot-name: 'Production'
          package: ./.net-app/
          
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2
        with:
          # The connection string, including authentication information, for the Azure SQL Server database.
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          # Path to the file used for this action. Supported file types are .sql, .dacpac, or .sqlproj.
          path:  D:\a\DeploymentAppWithDb\DeploymentAppWithDb/ddl-updates/sql-script.sql    
          
